### ISSUE TITLE
Поток от Axis

### ISSUE THREAD

**Issue by Dreadeath** [vladpen/python-rtsp-server#3]
Приветствую. Не могу проиграть VLC поток от сервера. Поток от камеры отдается по вот такому адресу rtsp://login:password@192.168.1.2:554/axis-media/media.amp

В storage пишется, отдельно поток VLC воспроизводит, а вот через сервер вида rtsp://ip:4554/hash выдает ошибку 
Client: error: can't handle request from 192.168.1.176: Invalid track ID in reply

С хиквижн работало, с аксисом не хотит :( Куда копать?

**Comment by Dreadeath** [comment]
Покопался, нашел. В camera.py меняем 243 строку на 
`track_ids = re.findall(r'\na=control:.*?(track|stream.*?\d)', reply, re.DOTALL)`
 и аксис подхватывается.

**Comment by vladpen** [comment]
Спасибо большое. Как будет время, обязательно посмотрю.
