### ISSUE TITLE
Client: error: can't handle request from 192.168.0.109: invalid camera hash

### ISSUE THREAD

**Issue by ardeal** [vladpen/python-rtsp-server#5]
Hi,
when I run python main.py, and then `vlc rtsp://192.168.0.105:4554/camera-has`, I see the following error:
`Client: error: can't handle request from 192.168.0.109: invalid camera hash`

by the way,
I installed a usb cam to ARM board, and then I would like to use your code to read the cam without decoding and send the data as rtsp. I changed the cameras in config.py file as follows:
```Python
    cameras = {
        'some-URL-compatible-string/including-UTF-characters': {
            'path': '.',
            'url': 'rtsp://192.168.0.105:4554/<uri>',
            # 'storage_command': 'any *nix command for saving rtsp stream to a file',
        },
    }
```

**Comment by vladpen** [comment]
Hi, welcome to the project!

Are you sure your url is correct? I can't see the "camera-has" key in your config..

**Comment by vladpen** [comment]
No response.
