### ISSUE TITLE
IP хоста

### ISSUE THREAD

**Issue by Dreadeath** [vladpen/python-rtsp-server#8]
https://github.com/vladpen/python-rtsp-server/blob/ced9c689c13bb5ee927f4d346a0edb846d75e4c5/client.py#L27

Вот тут жестко забито 0.0.0.0, хотелось бы менять адрес, где слушать, в конфиге. Я кстати думал, что это local_ip в конфиге, в общем немного путано в этом плане на мой взгляд.

**Comment by vladpen** [comment]
Да, local_ip в конфиге немного сбивает с толку. Насколько я помню, в одной из первых конфигураций использовался туннель для проброса из локальной сети на белый IP (для просмотра камер через интернет), но локальные клиенты, конечно, тоже могли подключаться. Поэтому в коде отрабатывается этот случай.

Можете подробнее расписать ваш вариант использования: зачем вам понадобилось ограничивать прослушивание порта "rtsp_port"?

**Comment by Dreadeath** [comment]
Для туннеля и надо, но чтоб и в локальную сеть ничего без разрешения не отдавалось, аутентификации-то нету. Плюс айпишников может много разных быть у сервера, в некоторых случаях даже белых.

Может, несколько гибче сделать? Скажем, угадывать локальный IP из подсети 192.168? В моем случае я поменял на 127.0.0.1, цель - подключаться через туннель, через ConnectBot, через Cams. Папок и тегов вы так и не завезли, приходится мастерить из того, что есть ;) Пока пробую и вроде пашет, но надо больше тестировать.

**Comment by vladpen** [comment]
Спасибо, понятно.

Вынес в конфиг параметр Config.rtsp_host.

По поводу локального IP - это и есть адрес машины в подсети. Если мне не изменяет память, используется для общения с камерами и/или заменяет локальный адерс камеры в ответах клиенту. Насколько я помню, это значение не критично и скорее всего его можно заменить любой ерундой, но это не точно (требует тестирования).

Что касается папок, тегов, авторизации и вообще развития - времени на этот проект нет, но пулл-реквесты принимаются:)

Вообще, в последнее время максимально развивается соседний проект cams-pwa. По моим наблюдениям, если пользователям дать выбор, они будут пользоваться именно им. Причины такого выбора понятны - там больше функционала (нативно интегрирована работа с архивами и детекторы движения), плюс работает на любой железке (с аппаратным декодером HEVC). Кроме того, несколько камер проксировать проще - достаточно один ip:port расшарить для всех камер сразу.

**Comment by vladpen** [comment]
Спасибо, понятно.

Вынес в конфиг параметр Config.rtsp_host.

По поводу локального IP - это и есть адрес машины в подсети. Если мне не изменяет память, используется для общения с камерами и/или заменяет локальный адерс камеры в ответах клиенту. Насколько я помню, это значение не критично и скорее всего его можно заменить любой ерундой, но это не точно (требует тестирования).

Что касается папок, тегов, авторизации и вообще развития - времени на этот проект нет, но пулл-реквесты принимаются:)

Вообще, в последнее время максимально развивается соседний проект cams-pwa. По моим наблюдениям, если пользователям дать выбор, они будут пользоваться именно им. Причины такого выбора понятны - там больше функционала (нативно интегрирована работа с архивами и детекторы движения), плюс работает на любой железке (с аппаратным декодером HEVC). Кроме того, несколько камер проксировать проще - достаточно один ip:port расшарить для всех камер сразу.

**Comment by Dreadeath** [comment]
cams-pwa не смотрел, в свое время смутило, что это веб-сервис. Надо присмотреться.

За коммит спасибо
