### ISSUE TITLE
I want to send face recognition frames

### ISSUE THREAD

**Issue by hoangsavitar** [vladpen/python-rtsp-server#9]
i want to send face recognition frames but i don't know where to edit. I tried the _interleave, _handle and write functions but it doesn't seem to edit the frames sent to the client. How can I edit frames directly before the client receives them? Can you tell me? I've been searching for 3 days but it still doesn't work

**Comment by vladpen** [comment]
This app is intended for traffic proxying. Only some headers are modified in accordance with the RTSP protocol. The app transmits raw streams and knows nothing about frames, fragments, or segments.

To be able to analyze an image, you need at least to combine the header information with the data stream.

**Comment by hoangsavitar** [comment]
Thank you for replying me. As far as I understand I at least need to combine the header information with the data stream. But I don't understand the async def write(self, frame) function. It still has a frame and when I use frame editing in that function, it doesn't work. Can you explain me more carefully when to use async def write(self, frame) and which frames are in it? And if I want to create an rtsp server that has applied the AI ​​model from the original rtsp, what should I do? Can you give me the right instructions to combine the header information with the data stream? I really thank you very much

**Comment by vladpen** [comment]
Sorry, I have no experience with openCV. But as far as I know, it is possible to connect directly to the camera, for example:
stream = cv2.VideoCapture(RTSP_URL, some_flags).

Than, if you call stream.read(), it will return a frame.

I can assume that you need to process and distribute the modified frames to clients.
